In [4]:
import numpy as np

# ============================================================
# PART A — Neural Network using NumPy
# ============================================================

def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def sigmoid_derivative(a):
    return a * (1 - a)


# XOR dataset
inputs = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

expected_output = np.array([
    [0],
    [1],
    [1],
    [0]
])


# Network: 2 input -> 2 hidden -> 1 output
inN, hidN, outN = 2, 2, 1

# Random initialization
np.random.seed(42)

hidden_weights = np.random.uniform(size=(inN, hidN))
hidden_bias = np.random.uniform(size=(1, hidN))

output_weights = np.random.uniform(size=(hidN, outN))
output_bias = np.random.uniform(size=(1, outN))

lr = 0.1


# Training
for epoch in range(10000):

    # ---- Forward ----
    h_out = sigmoid(
        np.dot(inputs, hidden_weights) + hidden_bias
    )

    predicted_output = sigmoid(
        np.dot(h_out, output_weights) + output_bias
    )

    # ---- Backward ----
    error = expected_output - predicted_output

    d_out = (
        error * sigmoid_derivative(predicted_output)
    )

    d_hid = (
        d_out.dot(output_weights.T)
        * sigmoid_derivative(h_out)
    )

    # ---- Update ----
    output_weights += (
        h_out.T.dot(d_out) * lr
    )

    output_bias += (
        np.sum(d_out, axis=0, keepdims=True) * lr
    )

    hidden_weights += (
        inputs.T.dot(d_hid) * lr
    )

    hidden_bias += (
        np.sum(d_hid, axis=0, keepdims=True) * lr
    )


# NumPy results
print("========== PART A: NUMPY ==========")

print("Predicted output:")
print(np.round(predicted_output, 3))

print("\nRounded prediction:")
print(np.round(predicted_output).astype(int))


# ============================================================
# PART B — Same XOR problem using Keras
# ============================================================

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD


# XOR dataset
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

y = np.array([
    [0],
    [1],
    [1],
    [0]
])


# Create model
model = Sequential()

# Hidden layer
model.add(
    Dense(
        8,
        input_dim=2,
        activation='relu'
    )
)

# Output layer
model.add(
    Dense(
        1,
        activation='sigmoid'
    )
)


# Compile model
model.compile(
    loss='binary_crossentropy',
    optimizer=SGD(learning_rate=0.1),
    metrics=['accuracy']
)


# Train model
model.fit(
    X,
    y,
    epochs=1000,
    verbose=0
)


# Evaluate model
loss, acc = model.evaluate(
    X,
    y,
    verbose=0
)


# Keras results
print("\n========== PART B: KERAS ==========")

print(f"Accuracy: {acc * 100:.2f}%")

predictions = model.predict(X, verbose=0)

print("\nPredicted output:")
print(np.round(predictions, 3))

print("\nRounded prediction:")
print(np.round(predictions).astype(int))


========== PART A: NUMPY ==========
Predicted output:
[[0.053]
 [0.952]
 [0.952]
 [0.052]]

Rounded prediction:
[[0]
 [1]
 [1]
 [0]]

========== PART B: KERAS ==========
Accuracy: 100.00%

Predicted output:
[[0.037]
 [0.989]
 [0.989]
 [0.037]]

Rounded prediction:
[[0]
 [1]
 [1]
 [0]]
